[build-system]
# Minimum requirements for the build system to execute (copied from ObsPy)
requires = [
    'setuptools'
]
build-backend = "setuptools.build_meta"

[project]
name = "wyrm"
version = "0.0.0"
authors = [
    {name="Nathan T. Stevens", email="ntsteven@uw.edu"},
    {name="Pacific Northwest Seismic Network", email="pnsn.org"}
]
description = "A python package connecting Earthworm messages and Python ML workflows"
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: AGPL-3.0 :: GNU General Public License",
    "Operating System :: ISTI Earthworm Compliant"
]

[project.urls]
Homepage = "https://github.com/pnsn/wyrm"
Issues = "https://github.com/pnsn/wyrm/issues"