[tool.hatch]
name="wyrm"
version="0.0.0"
description="Wyrm - Earthworm + Python + Torch"
authors = ["Nathan Stevens ntsteven@uw.edu"]

[tool.hatch.dependencies]
python = "^3.8"

[tool.hatch.package]
name="wyrm"
version="0.0.0"

[[tool.hatch.package.files]]
path="core"
include=["*.py"]

[[tool.hatch.package.files]]
path="util"
include=["*.py"]

[[tool.hatch.package.files]]
path="modules"
include=["*.py"]

[[tool.hatch.package.files]]
path="scripts"
include=["*.py"]


